[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"

[".config/tmux/plugins/catppuccin/tmux"]
type = "git-repo"
url = "https://github.com/catppuccin/tmux.git"
refreshPeriod = "168h"
