#!/usr/bin/env zsh

# XDG base directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# set editor to neovim
export EDITOR='nvim'
export VISUAL='nvim'

# set zsh config location
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTSIZE=10000
export SAVEHIST=10000

# fzf
export FZF_COLOR_SCHEME=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796"

# setup cargo
. "$HOME/.cargo/env"
