#!/usr/bin/env zsh

# NOTE: Env variables go into ~/.zshenv

# zgenom - zsh plugin manager
[ ! -f "$ZDOTDIR/.zgenom/zgenom.zsh" ] && git clone https://github.com/jandamm/zgenom.git "$ZDOTDIR/.zgenom"
source "$ZDOTDIR/.zgenom/zgenom.zsh"

zgenom autoupdate

if ! zgenom saved; then
  zgenom ohmyzsh

  zgenom ohmyzsh plugins/git
  zgenom ohmyzsh plugins/docker

  if command -v brew &> /dev/null; then zgenom ohmyzsh plugins/brew; fi

  zgenom load zsh-users/zsh-syntax-highlighting
  zgenom load zsh-users/zsh-autosuggestions
  zgenom load zsh-users/zsh-completions
  zgenom load unixorn/fzf-zsh-plugin

  zgenom load "$XDG_CONFIG_HOME/zsh/aliases"

  zgenom compile "$ZDOTDIR/.zshrc"
fi

# homebrew
if [ -f /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# mise - package manager for tooling
if command -v mise &>/dev/null; then
  eval "$(mise activate zsh)"
fi

# zoxide - remembers folders I cd into often
if command -v zoxide &>/dev/null; then
  eval "$(zoxide init zsh)"
fi

# starship prompt
if command -v starship &>/dev/null; then
  eval "$(starship init zsh)"
fi

# Set neovim as man pager if available
if command -v nvim &>/dev/null; then
  export MANPAGER='nvim +Man!'
fi

# Jetbrains
export PATH="$PATH:$HOME/Library/Application Support/JetBrains/Toolbox/scripts"
