import = [
  # uncomment the flavour you want below:
  # '~/.config/alacritty/catppuccin-mocha.toml'
  '~/.config/alacritty/catppuccin-macchiato.toml',
]

[window]
padding.x = 3
padding.y = 3
dynamic_padding = true

title = 'Alacritty'
dynamic_title = false

option_as_alt = 'Both'

[font]
normal.family = 'MonaspiceNe Nerd Font'
size = 14
offset.y = 2
