import = [
  # uncomment the flavour you want below:
  # '~/.config/alacritty/catppuccin-mocha.toml'
  '~/.config/alacritty/catppuccin-macchiato.toml'
]

live_config_reload = true

[window]
option_as_alt = 'Both'

[window.padding]
x = 4
y = 4

[font]
size = 14

[font.normal]
family = 'MesloLGS NF'
